### ISSUE TITLE
Messup in the Industries

### ISSUE THREAD

**Issue by ian76g** [JachyHm/ARRTools#1]
during parsing of your better.json I have to aplpy the following "patch" to make the industries come up on the right spot(s)
no idea what happend there :-(

`foreach($data['Industries'] as $site){

    $xoff = $yoff = 0;
    switch($site['Type']) {
        case 'CargoDepot':
            $name = 'Logging Camp';
            $rotation = 0;
            $xoff = -70;
            $yoff = -30;
            break;
        case 'LoggingCamp':
            $name = 'Sawmill';
            $rotation = 45;
            break;
        case 'Sawmill':
            $name = 'Smelter';
            $rotation = 90;
            break;
        case 'Smelter':
            $name = 'Ironworks';
            $rotation = 90;
            break;
        case 'IronMine':
            $name = 'Oilfield';
            $rotation = 0;
            break;
        case 'CoalMine':
            $name = 'Refinery';
            $rotation = 0;
            break;
        case 'Ironworks':
            $name = 'Coal Mine';
            $rotation  = -20;
            $xoff = -20;
            $yoff = 20;
            break;
        case 'Oilfield':
            $name = 'Iron Mine';
            $rotation = 45;
            $yoff = +50;
            $xoff = -20;
            break;
        case 'Refinery':
            $name = 'Cargo Depot';
            $rotation = 90;
            break;
        case 'Firewood':
            $name = 'F';
            $rotation = 0;
            break;
    }
`

**Comment by JachyHm** [comment]
Wrong Industry type already resolved in dcbed73.
Industries are objects spawned at coordinates and rotation from save file, however the mesh itself may be rotated and/or shifted too.
This should be however done yet in map drawing code, rather than in save converter.
